-- MySQL Script generated by MySQL Workbench
-- Mon Oct 25 14:57:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moovmidia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema moovmidia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moovmidia` ;
USE `moovmidia` ;

-- -----------------------------------------------------
-- Table `moovmidia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(500) NOT NULL,
  `criado_em` VARCHAR(45) NOT NULL,
  `editado_em` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`condutores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`condutores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `ativo` TINYINT NOT NULL DEFAULT 1,
  `carro` TEXT NOT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC),
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_condutores_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_condutores_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `moovmidia`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`administradores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_administradores_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_administradores_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `moovmidia`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`campanhas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`campanhas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_finalizacao` DATETIME NOT NULL,
  `posicao_inferior` TINYINT NOT NULL DEFAULT 0,
  `posicao_principal` TINYINT NOT NULL DEFAULT 0,
  `ativo` TINYINT NOT NULL DEFAULT '1',
  `criado_em` DATETIME NOT NULL,
  `editado_em` DATETIME NOT NULL,
  `arquivo` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`programacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`programacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `criado_em` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`blocos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`blocos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `programacoes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_blocos_programacoes1_idx` (`programacoes_id` ASC),
  CONSTRAINT `fk_blocos_programacoes1`
    FOREIGN KEY (`programacoes_id`)
    REFERENCES `moovmidia`.`programacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moovmidia`.`slots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `moovmidia`.`slots` (
  `id` INT NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_final` TIME NOT NULL,
  `criado_em` DATETIME NOT NULL,
  `blocos_id` INT NOT NULL,
  `campanhas_id` INT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_slots_blocos1_idx` (`blocos_id` ASC),
  INDEX `fk_slots_campanhas1_idx` (`campanhas_id` ASC),
  CONSTRAINT `fk_slots_blocos1`
    FOREIGN KEY (`blocos_id`)
    REFERENCES `moovmidia`.`blocos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slots_campanhas1`
    FOREIGN KEY (`campanhas_id`)
    REFERENCES `moovmidia`.`campanhas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
